Repository CodeForAfrica/harassment-manager, pull requests merged in 2022-10, with the labels that each got.

#8 Fix support pages
  src/app/find-support-list-item/find-support-list-item.component.scss
  src/app/find-support-tile/find-support-tile.component.scss
  src/app/find-support/find-support.component.html
  src/app/find-support/find-support.component.scss
  src/app/help-center/help-center.component.html
  src/app/help-center/help-center.component.scss
  src/app/privacy-page/privacy-page.component.html
  src/app/privacy-page/privacy-page.component.scss
  src/app/scrollable-side-menu/scrollable-side-menu.component.html
  src/app/scrollable-side-menu/scrollable-side-menu.component.scss
  src/app/toolbar/toolbar.component.scss
  src/app/welcome-page/welcome-page.component.html
  src/app/welcome-page/welcome-page.component.scss
  src/assets/1st Illustration.svg
  src/assets/Illustration.svg
  src/assets/bullet.svg
  src/assets/find_support_illustration.svg
  src/assets/header_cta.svg
  src/assets/header_illustration.svg
  src/assets/help_center.svg
  src/assets/help_center_illustration.svg
  src/assets/privacy_illustration.svg
Labels: bug, enhancement

#9 Improve security
  .gitignore
  app.yaml
  src/app/gapi.service.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: chore, enhancement

#10 Implement 404 page
  src/app/app-routing.module.ts
  src/app/not-found-page/not-found-page.component.html
  src/app/not-found-page/not-found-page.component.scss
  src/app/not-found-page/not-found-page.component.spec.ts
  src/app/not-found-page/not-found-page.component.ts
  src/app/toolbar/toolbar.component.scss
Labels: enhancement

#7 ft/UI-Update 2
  .gitignore
  app.yaml
  src/app/gapi.service.ts
  src/app/home-page/home-page.component.html
  src/app/home-page/home-page.component.scss
  src/app/intro-stepper/intro-stepper.component.html
  src/app/intro-stepper/intro-stepper.component.scss
  src/app/intro-stepper/intro-stepper.component.ts
  src/app/loading-dialog/loading-dialog.component.scss
  src/app/recommended-report-card/recommended-report-card.component.html
  src/app/recommended-report-card/recommended-report-card.component.scss
  src/app/toolbar/toolbar.component.html
  src/app/toolbar/toolbar.component.scss
  src/assets/add-all-icon.svg
  src/assets/all_comments_icon.svg
  src/assets/evidence_illustration.svg
  src/assets/eye-icon.svg
  src/assets/high_priority_icon.svg
  src/assets/possible_priority_icon.svg
  src/assets/review_illustration.svg
  src/assets/unknown_priority_icon.svg
  src/assets/welcome_illustration.svg
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/styles.scss
Labels: enhancement
